### ISSUE TITLE
NPE -  Minecraft Version 1.19.4

### ISSUE THREAD

**Issue by Rysefoxx** [aematsubara/InventoryUpdate#5]
In 1.19.4 the following code is null:

`
        activeContainer = getField(ENTITY_PLAYER, CONTAINER, "activeContainer", "bV", "bW", "bU", "containerMenu");`

**Comment by Xienox** [comment]
Can confirm, having the same issue with that exact line of code being the cause.

**Comment by aematsubara** [comment]
fixed
